# GitHub Actions ê³µì‹ documentation: https://docs.github.com/en/free-pro-team/actions
# sshì— shell script ì‹¤í–‰í•˜ê¸°: https://github.com/fifsky/ssh-action/blob/master/entrypoint.sh

name: Deploy master branch

on:
  push:
    branches: [master]

jobs:
  Deploy:
    runs-on: ubuntu-16.04
    env:
      DEPLOY_SCRIPT: shell.sh
      DEPLOY_KEY: deploy_key
    steps:
      - name: Make deploy script
        run: |
          cat << EOF > $DEPLOY_SCRIPT          
          echo "=== pull master branch ==="
          cd ${{ secrets.SSH_WORKING_DIRECTORY }}/src
          git checkout master
          git fetch origin master
          BE_DIFF=\$(git diff HEAD..origin/master --name-only -- ./backend | wc -l)
          FE_DIFF=\$(git diff HEAD..origin/master --name-only -- ./frontend | wc -l)
          git pull origin master
          
          echo "::group::Build & run backend application"
          if [ \$BE_DIFF -ne 0 ] ; then
            echo -e "\n=== build backend ==="
            cd backend
            npm ci || exit 1
            npm run build || exit 1
            echo -e "\n=== restart backend server ==="
            forever stopall
            forever start ./dist/app.js
            cd ..
          else
            echo "- Backend code not changed; step skipped."
          fi
          echo "::endgroup::"
          
          echo "::group::Build & run frontend application"
          if [ \$FE_DIFF -ne 0 ] ; then
            echo -e "\n=== build frontend ==="
            cd frontend
            npm ci || exit 1
            npm run build || exit 1
            echo -e "\n=== update nginx serve files ==="
            # rm -rf ${{ secrets.NGINX_DIRECTORY }}
            sudo cp -r ./dist/* ${{ secrets.NGINX_DIRECTORY }}
            cd ..
          else
            echo "- Frontend code not changed; step skipped."
          fi
          echo "::endgroup::"
          
          echo -e "\n=== All doneğŸš€ ==="
          EOF

      - name: Setting ssh agent and key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > $DEPLOY_KEY
          chmod 600 $DEPLOY_KEY

      - name: Run script on ssh
        run: ssh -i $DEPLOY_KEY -o StrictHostKeyChecking=no ${{ secrets.SSH_ORIGIN }} < $DEPLOY_SCRIPT

      - name: Cleanup
        if: ${{ always() }}
        run: |
          rm -f $DEPLOY_SCRIPT
          rm -f $DEPLOY_KEY
